__author__ = 'Derek Nicol <1420397+derekn@users.noreply.github.com>'
__version__ = '1.8.4'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Derek Nicol'
__url__ = 'https://github.com/derekn/blshift.git'
